# config.yaml
flask:
  secret_key: ""

# Amazon Cognito > User pools > User pool > App clients > App client > Quick Setup Guide & App client information 참고
cognito:
  authority: ""
  client_id: ""
  client_secret: ""
  metadata_url: ""
  region: ""
